"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation/Header
    "settings": "Settings",
    "logout": "Logout",
    "reminders": "Reminders",
    "browser": "Browser",
    "resources": "Resources",
    "chat": "Chat",
    "inbox": "Inbox",
    "espresso": "Espresso",
    "daily_recap": "Daily Recap",
    "crm": "CRM",
    "mission_control": "MISSION CONTROL",
    "super_admin_view": "Super Admin View",
    "global_progress": "Global Progress",
    "user_id": "User ID",
    "tier": "Tier",
    "last_active": "Last Active",
    "status": "Status",
    "active": "Active",
    "good_morning": "🌅 Good Morning!",
    "choose_tasks": "Choose your high-leverage tasks for today",
    "ultra_mode_active": "🔥 Ultra Mode Active",
    "activate_ultra_mode": "⚡ Activate Ultra Mode",
    "tier_progress": "Tier {tier} Progress",
    "complete_tasks_unlock": "Complete tasks to unlock the next tier.",
    "ultra_mode_desc": " 🔥 Ultra Mode: 20% harsher KPIs, more rewards!",
    "leverage": "Leverage",
    "kpi_target": "KPI Target",
    "selected_count": "Selected: {count} tasks",
    "skip_now": "Skip for now",
    "start_day": "Start Day",
    "start": "Start",
    "mission": "Mission",
    "notifications": "Notifications",
    "passed": "PASSED",
    "rejected": "REJECTED",
    "pending_review": "PENDING REVIEW",
    "filled": "FILLED",
    "fill_form": "FILL FORM",
    "under_review_alert": "This form is currently under review or approved and cannot be edited.",
    "submission_failed_alert": "Failed to submit document. Please try again.",
    "loading_mission_control": "Loading mission control...",
    "inbox_link_note": "* Document review and approvals are handled in the Inbox.",
    "documents": "Documents",
    "daily_tasks": "Daily Tasks",
    "permits_public": "Permits & Public",
    "competition_analysis": "Competition Analysis",
    "lot_activation_list": "Lot Activation List",
    "airport_analysis": "Airport Analysis",
    "stakeholder_analysis": "Stakeholder Analysis",
    "area_analysis": "Area Analysis",
    "hub_activation_form": "HUB Activation Form",
    "fill_permits_task": "Fill Permits & Public Form",
    "fill_competition_task": "Fill Competition Analysis Form",
    "fill_lot_activation_task": "Fill Lot Activation List",
    "fill_area_analysis_task": "Fill Area Analysis",
    "fill_airport_analysis_task": "Fill Airport Analysis",
    "fill_hotel_analysis_task": "Fill Hotel Analysis",
    "fill_whales_analysis_task": "Fill Whales Corporation Analysis",
    "hotel_analysis_placeholder": "Analyze the hotel landscape in your area. Who are the key players? What are their parking needs? How can we approach them?",
    "whales_analysis_placeholder": "Analyze the major corporations (Whales) in your area. What is their parking situation? Who are the decision makers?",
    "inbox_admin_mode": "INBOX (Admin Mode)",
    "loading": "Loading...",
    "no_items": "No items.",
    "no_reminders": "No reminders scheduled.",
    "from_label": "From: {sender}",
    "action_required": "Action Required",
    "review_grade": "Review & Grade",
    "review_prefix": "[REVIEW]",
    "submission_prefix": "Submission",
    "email_prefix": "Email",
    "review": "REVIEW",
    "submission": "Submission",
    "approve_submission_confirm": "Are you sure you want to approve this Tier {tier} submission?",
    "submission_approved_advance_alert": "Submission approved. User has completed all requirements for Tier {tier} and has been advanced to Tier {nextTier}.",
    "submission_approved_missing_alert": "Submission approved. User still needs to complete: {missing} to advance.",
    "submission_approved_alert": "Submission approved and user progressed.",
    "approval_failed_alert": "Failed to approve submission.",
    "unknown_user": "Unknown User",
    "document_submission_subject": "[REVIEW] Document Submission: Tier {tier} ({type})",
    "completed": "Completed",
    "no_users": "No active users found.",
    "inbox_note": "* Document review and approvals are handled in the Inbox.",
    
    // Settings Page
    "credentials": "Credentials",
    "general": "General",
    "language": "Language",
    "mobile_app": "Mobile App",
    "language_toggle_desc": "Toggle between English and Croatian.",
    "download_android": "Download our official Android app for full field operation support.",
    "download_apk": "Download Android APK",
    "user_label": "User",
    "no_email_label": "No email",
    "airport_land": "Airport land",
    "empty_land": "Empty land (City lots)",
    "crowded_lots": "Crowded Lots (Restaurants/Bars/Shops/Homeowners)",
    "villas_apartments": "Villas / Apartments",
    "single_power": "Single-power owners (Lots, Garages, Multi-Owners)",
    "hotels": "Hotels",
    "whales": "Whales (corporations / multi-decision)",
    "crm_contacts_status": "Contacts & Status",
    "search_contacts": "Search contacts...",
    "status_requirements": "Status Requirements",
    "entry": "Entry",
    "live_demo": "Live DEMO",
    "yes_date": "Yes Date",
    "no_date": "No Date",
    "follow_up_date_label": "Follow Up Date",
    "no_contacts": "No contacts in this tier.",
    "decision_maker": "Decision Maker",
    "location": "Location",
    "capacity": "Capacity",
    "tier_label": "Tier",
    
    // Notes
    "notes": "Notes",
    "no_notes": "No notes yet. Create one!",
    "title": "Title",
    "start_typing": "Start typing...",
    "untitled": "Untitled",
    "delete_note_confirm": "Are you sure you want to delete this note?",
    "unpin": "Unpin note",
    "pin": "Pin note",

    // Chat
    "ask_anything": "Ask...",
    "listening": "Listening...",
    "select_ai_model": "Select AI Model",
    "voice": "Voice",
    "select_conversation": "Select a conversation",
    "choose_chat": "Choose a chat from the sidebar or start a new one.",
    "task_added": "Task added",
    "task_removed": "Task removed",
    "task_completed": "Task completed",
    "task_confirmed": "Task confirmed",
    "task_not_found": "Task not found",
    "complete_before_confirm": "Complete the task before confirming",
    "auto_model": "Auto (Smart Switch)",
    "crm_updated": "CRM updated",
    "reminder_set_for": "Reminder set for",
    "native_alert_set": "Native Alert Set",
    "calendar_added": "+ Calendar",
    "native_error": "Native Error",
    "reminder_failed": "Failed to schedule reminder (Invalid time format from AI)",
    "reminder_mismatch": "AI confirmed a reminder verbally but failed to schedule it",
    "try_again": "Please try again",
    "completed_tasks": "Completed Tasks",
    "no_tasks_today": "No tasks completed today.",
    "crm_activity": "CRM Activity",
    "no_crm_today": "No new CRM contacts today.",
    "no_status": "No status",
    "advice_tomorrow": "Advice for Tomorrow",
    "close_rest": "Close & Rest",
    "tasks_list": "Tasks List",
    "no_tasks_yet": "No tasks yet.",
    "remove": "Remove",
    "confirm": "Confirm",
    "confirmed": "Confirmed",
    "tasks_done": "Tasks done",
    "current_tasks": "Current Tasks",
    "none": "None",
    "done": "Done",
    "performance": "Performance",
    "current_revenue": "Current Revenue",
    "lots_mapped": "Lots Mapped",
    "lots_activated": "Lots Activated",
    "strategic_initiatives": "Strategic Initiatives",
    "smart_city_program": "SMART CITY PROGRAM",
    "airport_hub_contract": "AIRPORT HUB (CONTRACT)",
    "city_hub_contract": "CITY HUB (CONTRACT)",
    "yes": "YES",
    "no": "NO",
    "quote_1": "Reflect on your wins today.",
    "quote_2": "Tomorrow is a new opportunity.",
    "quote_3": "Consistency is key.",
    "quote_4": "Small steps lead to big changes.",
    "quote_5": "Rest well, perform better tomorrow.",
    "quote_6": "Focus on what you can control.",
    "quote_7": "Every day is a chance to improve.",
    "quote_8": "Success is the sum of small efforts.",
    "quote_9": "Learn from today, plan for tomorrow.",
    "welcome_back": "Welcome back",
    "create_account": "Create an account",
    "sign_in": "Sign In",
    "create_account_btn": "Create Account",
    "full_name": "Full Name",
    "password": "Password",
    "sign_up_email": "Sign up with Email",
    "auth_error_generic": "An unexpected error occurred",
    "auth_confirmation_sent": "Confirmation email sent to {email}. Please check your spam folder.",
    "auth_missing_fields": "Please enter both email and password.",
    "auth_terms_agreement": "By clicking continue, you agree to our {terms} and {privacy}.",
    "terms": "Terms",
    "privacy": "Privacy Policy",
    "confirming_email": "Confirming your email…",
    "missing_confirmation_details": "Missing confirmation details.",
    "email_confirmed_close": "Email confirmed. You can close this tab.",
    // Mentorship
    "3_key_solutions": "3 KEY SOLUTIONS",
    "mentorship_solution_1_title": "1. Stopping unauthorized vehicles",
    "mentorship_solution_1_desc": "Authorization LPR system for complete parking control, greater security and rights for both owner and guests.",
    "mentorship_solution_2_title": "2. Less crowds",
    "mentorship_solution_2_desc": "We fill empty lots nearby, smart signs + taxi return ride.",
    "mentorship_solution_3_title": "3. Higher earnings",
    "mentorship_solution_3_item_1": "Visibility: SEO, GEO, landing page, Google Maps & Reviews",
    "mentorship_solution_3_item_2": "Conversion: bookings + dynamic pricing",
    "mentorship_solution_3_item_3": "Automation: LPR (faster entry/exit, lower cost)",
    "mentorship_solution_3_item_4": "Extra: insurance + taxi",
    "delete_reminder_confirm": "Are you sure you want to delete this reminder?",
    "clear_completed_confirm": "Are you sure you want to clear all completed reminders?",
    "enable_notifications": "Enable Notifications",
    "clear_completed": "Clear Completed",
    "notes_category": "Notes",
    "legal_finance": "Legal & Finance",
    "follow_up_materials": "Follow Up Materials",
    "mentorship_category": "Mentorship",
    "my_notes": "My Notes",
    "view_notes": "View Notes",
    "contracts": "Contracts",
    "invoices": "Invoices",
    "compliance": "Compliance",
    "legal_reference": "Legal Reference",
    "testimonials": "Testimonials",
    "demos": "Demos",
    "case_studies": "Case Studies",
    "audits": "Audits",
    "presentation": "Presentation",
    "security": "Security",
    "pricing": "Pricing",
    "product": "Product",
    "sales": "Sales",
    "sales_rules_label": "Sales & Contact Rules",
    "ops_mastery": "Ops Mastery",
    "non_negotiables": "Non-Negotiables",
    "review_management": "Review Management",
    "reviews_trust": "Reviews & Trust",
    "objection_handling": "Objection Handling",
    "common_objections_legal": "Common Objections & Legal Basis",
    "scripts": "Scripts",
    "personalized_outreach": "Personalized Outreach Framework",
    "three_biggest_problems": "3 Biggest Problems We Solve",
    "no_document": "No Document",
    "view_link": "View Link",

    // Objection Handling
    "common_objections_legal_title": "Common Objections & Legal Basis",
    "objection_1_title": "Objection #1: “Is this legal?”",
    "short_answer": "Short answer:",
    "yes_fully_legal": "Yes — fully legal.",
    "how_to_respond_verbatim": "How to respond (verbatim-safe):",
    "objection_1_resp_1": "We operate as a private parking company. All operational risk, enforcement costs, and liability are entirely ours, not the owner’s.",
    "objection_1_resp_2": "Under Croatian law, private parking operators are permitted to issue daily parking tickets. This is the same legal model used by:",
    "public_city_parking": "Public city parking companies",
    "private_parking_operators": "Private parking operators",
    "large_retail_chains": "Large retail and shopping chains using LPR / ANPR camera systems",
    "standard_framework": "Our practices follow the standard Croatian parking enforcement framework used nationwide.",
    "transparency_legal_terms": "For full transparency, guests are always directed to our Legal Terms & Parking Rules, published on our website.",
    "send_legal_page": "If you’d like, I can send you the exact legal page now.",
    "objection_2_title": "Objection #2: “This feels like a fine.”",
    "response_label": "Response:",
    "not_a_fine": "It is not a fine. Fines are issued by public authorities.",
    "daily_ticket_private": "This is a daily parking ticket issued under private parking terms — the same mechanism used by shopping centers and private garages across Croatia.",
    "objection_3_title": "Objection #3: “I didn’t see the signs.”",
    "signage_regulation": "Signage is placed according to regulation and visible at all entry points.",
    "prioritize_resolution": "However, if a guest feels confused or disadvantaged, we prioritize resolution, not punishment.",
    "refund_immediately": "If the guest asks for a refund → refund immediately.",
    "objection_4_title": "Objection #4: “Why is the price so high?”",
    "price_reflects": "The daily ticket price reflects:",
    "ops_24_7": "24/7 operations",
    "camera_infrastructure": "Camera infrastructure",
    "staff_support_logistics": "Staff, enforcement, support, and logistics",
    "immediate_assistance": "Immediate assistance and guaranteed uptime",
    "not_subsidized": "We do not operate as a city-subsidized service — all costs are ours.",
    "objection_5_title": "Objection #5: “I was only there for a short time.”",
    "automatic_detection": "The system operates automatically based on entry and exit detection.",
    "understand_mistakes": "However, we understand mistakes happen.",
    "policy_guest_first": "Our policy is guest-first — if the guest disputes the situation in good faith, we resolve it quickly and fairly.",
    "objection_6_title": "Objection #6: “Other parking places don’t do this.”",
    "many_do": "Many do — especially private operators, shopping centers, airports, and hotels using LPR systems.",
    "widely_accepted": "This is a widely accepted and legally established practice across Croatia and the EU.",
    "objection_7_title": "Objection #7: “I want to speak to someone in charge.”",
    "escalate_immediately": "Of course. We can escalate immediately.",
    "goal_resolution_minutes": "Our goal is resolution within minutes, not conflict.",
    "golden_rule_objections": "Golden Rule for All Objections",
    "de_escalate_first": "De-escalate first",
    "be_calm_discreet": "Be calm, discreet, and respectful",
    "never_argue_legality": "Never argue legality emotionally — state facts and redirect to written terms",
    "guest_insists_refund": "If a guest insists or feels stranded → refund immediately",
    "no_stranded_guest": "There is no scenario where a stranded guest is acceptable",
    "legal_basis_title": "Legal Basis: Mobile LPR Photos, App Security & Court Validity",
    "mobile_lpr_photography": "Mobile LPR (License Plate Recognition) Photography",
    "lpr_legal_interest": "Mobile LPR photos are legal and permitted under Croatian law when used for legitimate interest, such as private parking enforcement.",
    "license_plate_operational_data": "The vehicle license plate is treated as operational data, not sensitive personal data.",
    "photos_used_document": "Photos are used only to document:",
    "vehicle_presence": "Vehicle presence",
    "entry_exit_time": "Entry and exit time",
    "parking_duration": "Parking duration",
    "not_used_profiling": "They are not used for profiling or unrelated purposes.",
    "evidence_integrity_security": "Evidence Integrity & App Security",
    "enforcement_data_collected": "All enforcement data is collected through our secure internal app, which includes:",
    "automatic_timestamping": "Automatic timestamping (date & time locked at capture)",
    "gps_location_data": "GPS location data",
    "cryptographic_hash": "Cryptographic hash generated at the moment of capture",
    "tamper_proof_records": "Tamper-proof records (any modification invalidates the hash)",
    "ensures_label": "This ensures:",
    "photo_not_altered": "The photo cannot be altered retroactively",
    "time_place_provable": "The time and place of capture are provable",
    "evidence_chain_intact": "The evidence chain is intact",
    "legal_validity_court": "Legal Validity in Court",
    "verifiable_digital_evidence": "Each record forms a verifiable digital evidence package",
    "objectively_provable": "Time, location, and vehicle data are objectively provable",
    "legally_valid_enforceable": "Digital records and contracts generated this way are legally valid and enforceable in court",
    "evidentiary_standards": "This follows the same evidentiary standards used in:",
    "parking_disputes": "Parking disputes",
    "commercial_contract_enforcement": "Commercial contract enforcement",
    "automated_enforcement_systems": "Automated enforcement systems",
    "binding_private_contract": "Our Terms & Conditions, published on our website and accepted by use of the parking facility, form a binding private contract between the operator and the user.",

    // Ops Mastery
    "non_negotiables_title": "Non-Negotiables",
    "immediate_action": "Immediate Action",
    "immediate_solution": "Every push = immediate solution",
    "no_delays": "No delays, no callbacks, no excuses",
    "uptime_reliability": "Uptime & Reliability",
    "standard_100_uptime": "100% uptime is the standard",
    "stranded_guest_unacceptable": "A stranded guest is unacceptable — this must never happen",
    "response_time_slas": "Response Time SLAs",
    "max_5_min_ride": "Max 5 minutes ride waiting",
    "res_issues_15_min": "Reservation issues resolved within 15 minutes",
    "return_ride_15_min": "Return ride maximum 15 minutes",
    "same_day_tech": "Same-day technician arrival required",
    "guest_first_doctrine": "Guest First Doctrine",
    "guest_always_right": "The guest is always right",
    "avoid_conflict": "Avoid conflict — never farm fines",
    "partners_accountability": "Partners & Accountability",
    "top_tier_partners": "Only work with top-tier partners",
    "taxi_head_partner": "Taxi Head is the most important partner",
    "trained_agents": "Must have trained agents",
    "company_vetting": "Must pass full company vetting, even if personally chosen",
    "switch_immediately": "If reviews drop or uptime fails → switch immediately",
    "technician_rule": "Same rule applies to technicians:",
    "no_show_no_work": "No-show = no more work",
    "zero_tolerance_unreliability": "Zero tolerance for unreliability",
    "hub_launch": "HUB Launch",
    "reviews": "Reviews",
    "testing_marketing": "Testing / On Site Marketing / Allow Taxis to use the Lot",
    "feedback": "Feedback",
    "core_principle": "Core Principle",
    "stranded_guest_worst": "There is nothing worse than a stranded guest. Ops exist to ensure this never happens.",

    // Review Management
    "reviews_trust_manual": "Ultra-Brief Instruction Manual: Reviews & Trust",
    "check_reviews_daily": "Check reviews daily. Act fast—fresh issues grow quickly.",
    "remove_suspicious": "Remove suspicious items immediately. No debate: fake, unclear, or risky = gone.",
    "respond_clean_calm": "Respond clean & calm. Short, polite, solution-focused.",
    "surprise_moment": "One moment of surprise. Add on the terrain an unexpected positive landmark.",
    "cleanliness_matters": "Cleanliness matters. Visual order, tidy space, clear language.",
    "smile_matters": "Smile matters. Tone > words. Friendly always wins.",
    "speed_clarity_trust": "Rule: Speed, clarity, and trust beat perfection.",

    // Sales Rules
    "sales_contact_rules": "Sales & Contact Rules",
    "channels": "Channels",
    "channels_desc": "Phone, Email, SMS, WhatsApp — only if the user initiates contact via that channel.",
    "demo_trial": "Demo & Trial",
    "demo_trial_desc": "All demos, no-risk trials, and activations are live, in person, with the decision maker, on the first contact. If he is not there then call and try to set appointment never pitch on the phone but always say urgently what it is about.",
    "closing_phone": "Closing on the Phone",
    "closing_phone_desc": "Never close on the phone on the first contact. Phone is for setting appointment today/tommorow/term. Follow-Ups closes, and Upsells can be done by the phone but first contact never.",
    "next_step_discipline": "Next Step Discipline",
    "next_step_desc": "Every interaction must end with a scheduled call or meeting at an exact time. If more information is requested: send it immediately, then call the same day to close.",
    "appointments": "Appointments",
    "appointments_desc": "Appointments are set by phone only — today (danas) or tomorrow (sutra) if not possible schedule a term. No open-ended scheduling.",
    "speed_rule": "Speed Rule",
    "speed_rule_desc": "Call within 60 seconds of any response. If seen in person, close immediately if not schedule appointment call and follow up with more info immediately then try to close on the phone.",
    "lead_entry": "Lead Entry & Pre-Warm",
    "lead_entry_desc": "Initial prewarm contact should be via email if possible if not by the phone, then cold walk in PITCH phone appointment if not there. Walk Cold in Script through Digitisation + Grants, Empty Lot activation for empty land owners.",
    "objection_handling_rule": "Objection Handling",
    "objection_handling_desc": "If objections arise, log them into machine.io. If still “no,” ask: What would this need to have for you to say yes? Record the answer in machine.io.",
    "data_discipline": "Data Discipline",
    "data_discipline_desc": "Every interaction with a lead must be logged and described in Supabase / machine.io.",
    "conv_minimum": "Conversation Minimum",
    "conv_minimum_desc": "Aim for at least 1 minute of live conversation per contact — this lowers resistance.",
    "operator_support": "Operator Support",
    "operator_support_desc": "Use Chat for materials: emails, contracts, invoices, drafts, tactics, appearance guidance, reminders, complex WHALE sales, multi-demo flows, company research, and lobbying strategies.",
    "daily_improvement": "Daily Improvement",
    "daily_improvement_desc": "Learn the product every day. Improve it continuously.",
    "urgency_framing": "Urgency & Framing",
    "urgency_framing_desc": "Every prospect interaction is urgent and value-driven:",
    "unused_capacity": "You have unused capacity.",
    "stop_unauthorized": "I will stop unauthorized vehicles.",
    "increase_reviews": "I will increase reviews, revenue, safety, and digitization.",
    "eliminate_congestion": "I will eliminate congestion.",
    "decision_maker_rule": "Decision Maker Rule",
    "decision_maker_rule_desc": "No decision maker = no close. Always reach the decision maker.",

    // Scripts
    "personalized_outreach_framework": "Personalized Outreach Framework",
    "outreach_desc": "Must be written personally for each customer — this is about relationship depth, not automation.",
    "outreach_manual_work": "Doing this work manually for each guest changes how you think about sales: it builds trust, deepens engagement, and increases the likelihood of successful deal.",
    "reference_personalized": "1. Reference Personalized Situation (1 sentence)",
    "acknowledge_context": "Acknowledge the guest’s unique context or experience.",
    "present_solution": "2. Present Solution (1 sentence)",
    "state_fix": "State the fix confidently.",
    "attitude_fix": "Attitude: “This is a fix, not a suggestion.”",
    "ask_time_date": "3. Ask for Time/Date Meet-Up (1 sentence)",
    "schedule_follow_up": "Schedule a follow-up call or meeting to confirm the solution.",
    "attitude_professional": "Attitude: professional, confident, action-oriented.",
    "follow_up_same_day": "Follow-Up: Same day always",
    "send_personalized_note": "Send a personalized handwritten or AI-assisted PDF note thanking the guest and presenting all relevant info with links.",
    "daily_recap_title": "DAILY RECAP",
    "tasks_summary": "Tasks: {total} total, {completed} completed.",
    "no_detailed_records": "No detailed records for this date.",
    "from_label_prefix": "From:",
    "payparq_system": "PayParq System",
    "daily_recap_subject": "Daily Recap - {date}",
    "map_relevant_lots": "Map All Relevant Lots",
    "activate_1_lot_goal": "Activate 1 Lot (Try to close best first)",
    "fill_analysis": "Fill {type} Analysis",
    "hotel": "Hotel",
    "whales_corporation": "Whales Corporation",
    "airport": "Airport",
    "area": "Area",
  },
  hr: {
    // Navigation/Header
    "settings": "Postavke",
    "logout": "Odjava",
    "reminders": "Podsjetnici",
    "browser": "Preglednik",
    "resources": "Resursi",
    "chat": "Chat",
    "inbox": "Sandučić",
    "espresso": "Espresso",
    "daily_recap": "Dnevni pregled",
    "crm": "CRM",
    "mission_control": "KONTROLA MISIJE",
    "super_admin_view": "Super Admin Pogled",
    "global_progress": "Globalni napredak",
    "user_id": "Korisnički ID",
    "tier": "Razina",
    "last_active": "Zadnje aktivno",
    "status": "Status",
    "active": "Aktivno",
    "good_morning": "🌅 Dobro jutro!",
    "choose_tasks": "Odaberite svoje ključne zadatke za danas",
    "ultra_mode_active": "🔥 Ultra način aktivan",
    "activate_ultra_mode": "⚡ Aktiviraj Ultra način",
    "tier_progress": "Napredak na razini {tier}",
    "complete_tasks_unlock": "Dovršite zadatke za otključavanje sljedeće razine.",
    "ultra_mode_desc": " 🔥 Ultra način: 20% stroži KPI-jevi, više nagrada!",
    "leverage": "Učinak",
    "kpi_target": "KPI cilj",
    "selected_count": "Odabrano: {count} zadataka",
    "skip_now": "Preskoči za sada",
    "start_day": "Započni dan",
    "start": "Početna",
    "mission": "Misija",
    "notifications": "Obavijesti",
    "passed": "PROŠLO",
    "rejected": "ODBIJENO",
    "pending_review": "ČEKA PREGLED",
    "filled": "POPUNJENO",
    "fill_form": "POPUNI OBRAZAC",
    "under_review_alert": "Ovaj obrazac je trenutno na pregledu ili je odobren i ne može se mijenjati.",
    "submission_failed_alert": "Slanje dokumenta nije uspjelo. Molimo pokušajte ponovno.",
    "loading_mission_control": "Učitavanje kontrolne misije...",
    "inbox_link_note": "* Pregled i odobravanje dokumenata vrši se u Sandučiću.",
    "documents": "Dokumenti",
    "daily_tasks": "Dnevni zadaci",
    "permits_public": "Dozvole i javno",
    "competition_analysis": "Analiza konkurencije",
    "lot_activation_list": "Lista aktivacije parcela",
    "airport_analysis": "Analiza zračne luke",
    "stakeholder_analysis": "Analiza dionika",
    "area_analysis": "Analiza područja",
    "hub_activation_form": "Obrazac za aktivaciju HUB-a",
    "fill_permits_task": "Popunite obrazac za dozvole i javno",
    "fill_competition_task": "Popunite obrazac za analizu konkurencije",
    "fill_lot_activation_task": "Popunite listu aktivacije parcela",
    "fill_area_analysis_task": "Popunite analizu područja",
    "fill_airport_analysis_task": "Popunite analizu zračne luke",
    "fill_hotel_analysis_task": "Popunite analizu hotela",
    "fill_whales_analysis_task": "Popunite analizu Whales korporacije",
    "hotel_analysis_placeholder": "Analizirajte hotelski krajolik u svom području. Tko su ključni igrači? Koje su njihove potrebe za parkiranjem? Kako im možemo pristupiti?",
    "whales_analysis_placeholder": "Analizirajte velike korporacije (Whales) u svom području. Kakva je njihova situacija s parkiranjem? Tko su donositelji odluka?",
    "inbox_admin_mode": "SANDUČIĆ (Admin način)",
    "loading": "Učitavanje...",
    "no_items": "Nema stavki.",
    "no_reminders": "Nema zakazanih podsjetnika.",
    "from_label": "Šalje: {sender}",
    "action_required": "Potrebna radnja",
    "review_grade": "Pregledaj i ocjeni",
    "review_prefix": "[PREGLED]",
    "submission_prefix": "Podnesak",
    "email_prefix": "E-pošta",
    "review": "PREGLED",
    "submission": "Podnesak",
    "approve_submission_confirm": "Jeste li sigurni da želite odobriti ovaj podnesak za razinu {tier}?",
    "submission_approved_advance_alert": "Podnesak odobren. Korisnik je ispunio sve zahtjeve za razinu {tier} i napredovao je na razinu {nextTier}.",
    "submission_approved_missing_alert": "Podnesak odobren. Korisnik još treba ispuniti: {missing} za napredovanje.",
    "submission_approved_alert": "Podnesak odobren i korisnik je napredovao.",
    "approval_failed_alert": "Odobravanje podneska nije uspjelo.",
    "unknown_user": "Nepoznat korisnik",
    "document_submission_subject": "[PREGLED] Podnesak dokumenta: Razina {tier} ({type})",
    "completed": "Završeno",
    "no_users": "Nema aktivnih korisnika.",
    "inbox_note": "* Pregled dokumenata i odobrenja vrši se u Sandučiću.",

    // Settings Page
    "credentials": "Akreditivi",
    "general": "Općenito",
    "language": "Jezik",
    "mobile_app": "Mobilna aplikacija",
    "language_toggle_desc": "Prebacite između engleskog i hrvatskog jezika.",
    "download_android": "Preuzmite našu službenu Android aplikaciju za punu podršku operacijama na terenu.",
    "download_apk": "Preuzmi Android APK",
    "user_label": "Korisnik",
    "no_email_label": "Nema e-pošte",

    // CRM
    "airport_land": "Zemljište zračne luke",
    "empty_land": "Prazno zemljište (Gradske čestice)",
    "crowded_lots": "Prometne čestice (Restorani/Barovi/Trgovine/Vlasnici kuća)",
    "villas_apartments": "Vile / Apartmani",
    "single_power": "Vlasnici s jednim objektom (Čestice, Garaže, Suvlasnici)",
    "hotels": "Hoteli",
    "whales": "Kitovi (korporacije / multi-odlučivanje)",
    "crm_contacts_status": "Kontakti i status",
    "search_contacts": "Traži kontakte...",
    "status_requirements": "Zahtjevi statusa",
    "entry": "Ulaz",
    "live_demo": "DEMO uživo",
    "yes_date": "Datum 'Da'",
    "no_date": "Datum 'Ne'",
    "follow_up_date_label": "Datum praćenja",
    "no_contacts": "Nema kontakata u ovoj razini.",
    "decision_maker": "Donositelj odluka",
    "location": "Lokacija",
    "capacity": "Kapacitet",
    "tier_label": "Razina",

    // Notes
    "notes": "Bilješke",
    "no_notes": "Još nema bilješki. Kreirajte jednu!",
    "title": "Naslov",
    "start_typing": "Počnite tipkati...",
    "untitled": "Bez naslova",
    "delete_note_confirm": "Jeste li sigurni da želite obrisati ovu bilješku?",
    "unpin": "Odpni bilješku",
    "pin": "Prikvači bilješku",

    // Chat
    "ask_anything": "Započni...",
    "listening": "Slušam...",
    "select_ai_model": "Odaberi AI Model",
    "voice": "Glas",
    "select_conversation": "Odaberi razgovor",
    "choose_chat": "Odaberite chat iz bočne trake ili započnite novi.",
    "task_added": "Zadatak dodan",
    "task_removed": "Zadatak uklonjen",
    "task_completed": "Zadatak završen",
    "task_confirmed": "Zadatak potvrđen",
    "task_not_found": "Zadatak nije pronađen",
    "complete_before_confirm": "Dovršite zadatak prije potvrde",
    "auto_model": "Automatski (Pametni preklop)",
    "crm_updated": "CRM ažuriran",
    "reminder_set_for": "Podsjetnik postavljen za",
    "native_alert_set": "Lokalna obavijest postavljena",
    "calendar_added": "+ Kalendar",
    "native_error": "Greška sustava",
    "reminder_failed": "Neuspjelo postavljanje podsjetnika (Neispravan format vremena)",
    "reminder_mismatch": "AI je potvrdio podsjetnik usmeno, ali ga nije uspio zakazati",
    "try_again": "Molimo pokušajte ponovno",
    "completed_tasks": "Dovršeni zadaci",
    "no_tasks_today": "Danas nema dovršenih zadataka.",
    "crm_activity": "CRM aktivnost",
    "no_crm_today": "Danas nema novih CRM kontakata.",
    "no_status": "Nema statusa",
    "advice_tomorrow": "Savjet za sutra",
    "close_rest": "Zatvori i odmori",
    "tasks_list": "Lista zadataka",
    "no_tasks_yet": "Još nema zadataka.",
    "remove": "Ukloni",
    "confirm": "Potvrdi",
    "confirmed": "Potvrđeno",
    "tasks_done": "zadataka završeno",
    "current_tasks": "Trenutni zadaci",
    "none": "Nema",
    "done": "Završeno",
    "performance": "Učinak",
    "current_revenue": "Trenutni prihod",
    "lots_mapped": "Mapirane parcele",
    "lots_activated": "Aktivirane parcele",
    "strategic_initiatives": "Strateške inicijative",
    "smart_city_program": "SMART CITY PROGRAM",
    "airport_hub_contract": "AIRPORT HUB (UGOVOR)",
    "city_hub_contract": "CITY HUB (UGOVOR)",
    "yes": "DA",
    "no": "NE",
    "quote_1": "Razmislite o svojim današnjim uspjesima.",
    "quote_2": "Sutra je nova prilika.",
    "quote_3": "Dosljednost je ključ.",
    "quote_4": "Mali koraci vode do velikih promjena.",
    "quote_5": "Odmorite se dobro, sutra radite bolje.",
    "quote_6": "Fokusirajte se na ono što možete kontrolirati.",
    "quote_7": "Svaki dan je prilika za napredak.",
    "quote_8": "Uspjeh je zbroj malih napora.",
    "quote_9": "Učite od danas, planirajte za sutra.",
    "welcome_back": "Dobrodošli natrag",
    "create_account": "Kreirajte račun",
    "sign_in": "Prijavi se",
    "create_account_btn": "Kreiraj račun",
    "full_name": "Puno ime",
    "password": "Lozinka",
    "sign_up_email": "Registriraj se putem e-pošte",
    "auth_error_generic": "Došlo je do neočekivane pogreške",
    "auth_confirmation_sent": "Potvrdna e-poruka poslana je na {email}. Molimo provjerite svoju neželjenu poštu.",
    "auth_missing_fields": "Molimo unesite e-poštu i lozinku.",
    "auth_terms_agreement": "Klikom na Nastavi, slažete se s našim {terms} i {privacy}.",
    "terms": "Uvjetima korištenja",
    "privacy": "Pravilima o privatnosti",
    "confirming_email": "Potvrđivanje vaše e-pošte…",
    "missing_confirmation_details": "Nedostaju podaci za potvrdu.",
    "email_confirmed_close": "E-pošta potvrđena. Možete zatvoriti ovu karticu.",

    // Mentorship
    "3_key_solutions": "3 KLJUČNA RJEŠENJA",
    "mentorship_solution_1_title": "1. Zaustavljamo neautorizirana vozila",
    "mentorship_solution_1_desc": "Autorizacijski LPR sustav za potpunu kontrolu parkinga, veća sigurnost i prava i za vlasnika i goste.",
    "mentorship_solution_2_title": "2. Manje gužve",
    "mentorship_solution_2_desc": "Punimo prazne lotove u blizini, pametni znakovi + taksi povratna vožnja.",
    "mentorship_solution_3_title": "3. Veća zarada",
    "mentorship_solution_3_item_1": "Vidljivost: SEO, GEO, landing page, Google Maps & Reviews",
    "mentorship_solution_3_item_2": "Konverzija: rezervacije + dinamičke cijene",
    "mentorship_solution_3_item_3": "Automatika: LPR (brži ulaz/izlaz, manji trošak)",
    "mentorship_solution_3_item_4": "Dodatno: osiguranje + taxi",
    "delete_reminder_confirm": "Jeste li sigurni da želite obrisati ovaj podsjetnik?",
    "clear_completed_confirm": "Jeste li sigurni da želite ukloniti sve završene podsjetnike?",
    "enable_notifications": "Omogući obavijesti",
    "clear_completed": "Očisti završeno",
    "notes_category": "Bilješke",
    "legal_finance": "Pravno i financije",
    "follow_up_materials": "Materijali za praćenje",
    "mentorship_category": "Mentorstvo",
    "my_notes": "Moje bilješke",
    "view_notes": "Vidi bilješke",
    "contracts": "Ugovori",
    "invoices": "Računi",
    "compliance": "Usklađenost",
    "legal_reference": "Pravna referenca",
    "testimonials": "Iskustva korisnika",
    "demos": "Demo prikazi",
    "case_studies": "Studije slučaja",
    "audits": "Revizije",
    "presentation": "Prezentacija",
    "security": "Sigurnost",
    "pricing": "Cijene",
    "product": "Proizvod",
    "sales": "Prodaja",
    "sales_rules_label": "Pravila prodaje i kontakta",
    "ops_mastery": "Ovladavanje operacijama",
    "non_negotiables": "Stvari o kojima se ne pregovara",
    "review_management": "Upravljanje recenzijama",
    "reviews_trust": "Recenzije i povjerenje",
    "objection_handling": "Rješavanje prigovora",
    "common_objections_legal": "Uobičajeni prigovori i pravna osnova",
    "scripts": "Skripte",
    "personalized_outreach": "Okvir za personalizirani pristup",
    "three_biggest_problems": "3 najveća problema koja rješavamo",
    "no_document": "Nema dokumenta",
    "view_link": "Vidi poveznicu",

    // Objection Handling
    "common_objections_legal_title": "Uobičajeni prigovori i pravna osnova",
    "objection_1_title": "Prigovor br. 1: „Je li ovo legalno?”",
    "short_answer": "Kratak odgovor:",
    "yes_fully_legal": "Da — potpuno legalno.",
    "how_to_respond_verbatim": "Kako odgovoriti (sigurno za doslovnu upotrebu):",
    "objection_1_resp_1": "Djelujemo kao privatna parkirališna tvrtka. Sav operativni rizik, troškovi ovrhe i odgovornost u potpunosti su naši, a ne vlasnikovi.",
    "objection_1_resp_2": "Prema hrvatskom zakonu, privatnim operaterima parkiranja dopušteno je izdavanje dnevnih parkirališnih karata. To je isti pravni model koji koriste:",
    "public_city_parking": "Gradska komunalna poduzeća za parkiranje",
    "private_parking_operators": "Privatni operateri parkiranja",
    "large_retail_chains": "Veliki trgovački lanci i trgovački centri koji koriste LPR / ANPR sustave kamera",
    "standard_framework": "Naša praksa slijedi standardni hrvatski okvir za provedbu parkiranja koji se koristi u cijeloj zemlji.",
    "transparency_legal_terms": "Za potpunu transparentnost, goste se uvijek upućuje na naše Pravne uvjete i pravila parkiranja objavljena na našoj web stranici.",
    "send_legal_page": "Ako želite, mogu vam odmah poslati točnu pravnu stranicu.",
    "objection_2_title": "Prigovor br. 2: „Ovo mi se čini kao kazna.”",
    "response_label": "Odgovor:",
    "not_a_fine": "Ovo nije kazna. Kazne izdaju javna tijela.",
    "daily_ticket_private": "Ovo je dnevna parkirališna karta izdana prema privatnim uvjetima parkiranja — isti mehanizam koji koriste trgovački centri i privatne garaže diljem Hrvatske.",
    "objection_3_title": "Prigovor br. 3: „Nisam vidio znakove.”",
    "signage_regulation": "Signalizacija je postavljena prema propisima i vidljiva je na svim ulaznim točkama.",
    "prioritize_resolution": "Međutim, ako se gost osjeća zbunjeno ili zakinuto, prioritet nam je rješenje, a ne kažnjavanje.",
    "refund_immediately": "Ako gost zatraži povrat → izvršite povrat odmah.",
    "objection_4_title": "Prigovor br. 4: „Zašto je cijena tako visoka?”",
    "price_reflects": "Cijena dnevne karte odražava:",
    "ops_24_7": "Operacije 24/7",
    "camera_infrastructure": "Infrastruktura kamera",
    "staff_support_logistics": "Osoblje, provedba, podrška i logistika",
    "immediate_assistance": "Trenutna pomoć i zajamčena dostupnost",
    "not_subsidized": "Ne djelujemo kao gradski subvencionirana usluga — svi troškovi su naši.",
    "objection_5_title": "Prigovor br. 5: „Bio sam tamo samo kratko vrijeme.”",
    "automatic_detection": "Sustav radi automatski na temelju detekcije ulaska i izlaska.",
    "understand_mistakes": "Ipak, razumijemo da se pogreške događaju.",
    "policy_guest_first": "Naša politika je 'gost na prvom mjestu' — ako gost ospori situaciju u dobroj vjeri, rješavamo to brzo i pošteno.",
    "objection_6_title": "Prigovor br. 6: „Druga parkirališta to ne rade.”",
    "many_do": "Mnoga rade — posebno privatni operateri, trgovački centri, zračne luke i hoteli koji koriste LPR sustave.",
    "widely_accepted": "Ovo je široko prihvaćena i pravno utemeljena praksa diljem Hrvatske i EU.",
    "objection_7_title": "Prigovor br. 7: „Želim razgovarati s nekim nadređenim.”",
    "escalate_immediately": "Naravno. Možemo odmah eskalirati upit.",
    "goal_resolution_minutes": "Naš cilj je rješenje unutar nekoliko minuta, a ne sukob.",
    "golden_rule_objections": "Zlatno pravilo za sve prigovore",
    "de_escalate_first": "Prvo deeskalirajte",
    "be_calm_discreet": "Budite smireni, diskretni i puni poštovanja",
    "never_argue_legality": "Nikada se ne raspravljajte o legalnosti emocionalno — navedite činjenice i uputite na pisane uvjete",
    "guest_insists_refund": "Ako gost inzistira ili se osjeća bespomoćno → izvršite povrat odmah",
    "no_stranded_guest": "Ne postoji scenarij u kojem je ostavljanje gosta na cjedilu prihvatljivo",
    "legal_basis_title": "Pravna osnova: Mobilne LPR fotografije, sigurnost aplikacije i valjanost na sudu",
    "mobile_lpr_photography": "Mobilna LPR (prepoznavanje registarskih tablica) fotografija",
    "lpr_legal_interest": "Mobilne LPR fotografije su legalne i dopuštene prema hrvatskom zakonu kada se koriste za legitimni interes, kao što je provedba parkiranja na privatnom posjedu.",
    "license_plate_operational_data": "Registarska pločica vozila tretira se kao operativni podatak, a ne kao osjetljivi osobni podatak.",
    "photos_used_document": "Fotografije se koriste samo za dokumentiranje:",
    "vehicle_presence": "Prisutnost vozila",
    "entry_exit_time": "Vrijeme ulaska i izlaska",
    "parking_duration": "Trajanje parkiranja",
    "not_used_profiling": "Ne koriste se za profiliranje ili u nepovezane svrhe.",
    "evidence_integrity_security": "Integritet dokaza i sigurnost aplikacije",
    "enforcement_data_collected": "Svi podaci o provedbi prikupljaju se putem naše sigurne interne aplikacije, koja uključuje:",
    "automatic_timestamping": "Automatsko vremensko označavanje (datum i vrijeme zaključani u trenutku snimanja)",
    "gps_location_data": "GPS podaci o lokaciji",
    "cryptographic_hash": "Kriptografski hash generiran u trenutku snimanja",
    "tamper_proof_records": "Zapisi zaštićeni od neovlaštenih izmjena (svaka izmjena poništava hash)",
    "ensures_label": "To osigurava:",
    "photo_not_altered": "Fotografija se ne može naknadno mijenjati",
    "time_place_provable": "Vrijeme i mjesto snimanja su dokazivi",
    "evidence_chain_intact": "Lanac dokaza je netaknut",
    "legal_validity_court": "Pravna valjanost na sudu",
    "verifiable_digital_evidence": "Svaki zapis čini paket digitalnih dokaza koji se može provjeriti",
    "objectively_provable": "Vrijeme, lokacija i podaci o vozilu su objektivno dokazivi",
    "legally_valid_enforceable": "Digitalni zapisi i ugovori generirani na ovaj način pravno su valjani i utuživi na sudu",
    "evidentiary_standards": "Ovo slijedi iste dokazne standarde koji se koriste u:",
    "parking_disputes": "Sporovi oko parkiranja",
    "commercial_contract_enforcement": "Provedba komercijalnih ugovora",
    "automated_enforcement_systems": "Automatizirani sustavi provedbe",
    "binding_private_contract": "Naši Uvjeti i odredbe, objavljeni na našoj web stranici i prihvaćeni korištenjem parkirališta, čine obvezujući privatni ugovor između operatera i korisnika.",

    // Ops Mastery
    "non_negotiables_title": "Stvari o kojima se ne pregovara",
    "immediate_action": "Trenutna akcija",
    "immediate_solution": "Svaki potisak = trenutno rješenje",
    "no_delays": "Bez kašnjenja, bez povratnih poziva, bez isprika",
    "uptime_reliability": "Dostupnost i pouzdanost",
    "standard_100_uptime": "100% dostupnost je standard",
    "stranded_guest_unacceptable": "Ostavljanje gosta na cjedilu je neprihvatljivo — to se nikada ne smije dogoditi",
    "response_time_slas": "SLA vremena odziva",
    "max_5_min_ride": "Maksimalno 5 minuta čekanja na vožnju",
    "res_issues_15_min": "Problemi s rezervacijama riješeni unutar 15 minuta",
    "return_ride_15_min": "Povratna vožnja maksimalno 15 minuta",
    "same_day_tech": "Obavezan dolazak tehničara isti dan",
    "guest_first_doctrine": "Doktrina 'Gost na prvom mjestu'",
    "guest_always_right": "Gost je uvijek u pravu",
    "avoid_conflict": "Izbjegavajte sukobe — nikada ne 'sakupljajte' kazne",
    "partners_accountability": "Partneri i odgovornost",
    "top_tier_partners": "Radite samo s vrhunskim partnerima",
    "taxi_head_partner": "Taxi Head je najvažniji partner",
    "trained_agents": "Moraju imati obučene agente",
    "company_vetting": "Moraju proći potpunu provjeru tvrtke, čak i ako su osobno odabrani",
    "switch_immediately": "Ako recenzije padnu ili dostupnost zakaže → promijenite odmah",
    "technician_rule": "Isto pravilo vrijedi i za tehničare:",
    "no_show_no_work": "Nedolazak = nema više posla",
    "zero_tolerance_unreliability": "Nulta tolerancija za nepouzdanost",
    "hub_launch": "Lansiranje HUB-a",
    "reviews": "Recenzije",
    "testing_marketing": "Testiranje / Marketing na licu mjesta / Dopustite taksijima korištenje parcele",
    "feedback": "Povratne informacije",
    "core_principle": "Temeljno načelo",
    "stranded_guest_worst": "Nema ništa gore od gosta ostavljenog na cjedilu. Operacije postoje kako bi se osiguralo da se to nikada ne dogodi.",

    // Review Management
    "reviews_trust_manual": "Ultra-kratki priručnik: Recenzije i povjerenje",
    "check_reviews_daily": "Provjeravajte recenzije svakodnevno. Djelujte brzo—svježi problemi brzo rastu.",
    "remove_suspicious": "Odmah uklonite sumnjive stavke. Nema rasprave: lažno, nejasno ili rizično = briše se.",
    "respond_clean_calm": "Odgovarajte čisto i smireno. Kratko, pristojno, usmjereno na rješenje.",
    "surprise_moment": "Trenutak iznenađenja. Dodajte na terenu neočekivanu pozitivnu točku.",
    "cleanliness_matters": "Čistoća je važna. Vizualni red, uredan prostor, jasan jezik.",
    "smile_matters": "Osmijeh je važan. Ton > riječi. Ljubaznost uvijek pobjeđuje.",
    "speed_clarity_trust": "Pravilo: Brzina, jasnoća i povjerenje pobjeđuju savršenstvo.",

    // Sales Rules
    "sales_contact_rules": "Pravila prodaje i kontakta",
    "channels": "Kanali",
    "channels_desc": "Telefon, e-pošta, SMS, WhatsApp — samo ako korisnik inicira kontakt putem tog kanala.",
    "demo_trial": "Demo i proba",
    "demo_trial_desc": "Svi demo prikazi, probne verzije bez rizika i aktivacije odvijaju se uživo, osobno, s donositeljem odluke, pri prvom kontaktu. Ako on nije tamo, nazovite i pokušajte dogovoriti termin, nikada ne prezentirajte preko telefona, ali uvijek recite hitno o čemu se radi.",
    "closing_phone": "Zaključivanje preko telefona",
    "closing_phone_desc": "Nikada ne zaključujte prodaju preko telefona pri prvom kontaktu. Telefon služi za dogovaranje termina danas/sutra/rok. Naknadni pozivi, zaključivanja i prodaja dodatnih usluga mogu se obaviti telefonom, ali prvi kontakt nikada.",
    "next_step_discipline": "Disciplina sljedećeg koraka",
    "next_step_desc": "Svaka interakcija mora završiti zakazanim pozivom ili sastankom u točno određeno vrijeme. Ako se zatraži više informacija: pošaljite ih odmah, a zatim nazovite isti dan kako biste zaključili prodaju.",
    "appointments": "Termini",
    "appointments_desc": "Termini se dogovaraju isključivo telefonom — danas ili sutra, ako nije moguće, zakažite rok. Nema neodređenog zakazivanja.",
    "speed_rule": "Pravilo brzine",
    "speed_rule_desc": "Nazovite unutar 60 sekundi od bilo kojeg odgovora. Ako se vidite osobno, zaključite odmah, ako ne, dogovorite termin, nazovite i odmah pošaljite dodatne informacije, a zatim pokušajte zaključiti preko telefona.",
    "lead_entry": "Unos potencijalnih klijenata i zagrijavanje",
    "lead_entry_desc": "Inicijalni kontakt za zagrijavanje trebao bi biti putem e-pošte ako je moguće, ako ne, telefonom, zatim hladni dolazak (PITCH) i dogovaranje termina ako donositelj odluke nije tamo. Skripta za hladni dolazak kroz digitalizaciju + potpore, aktivacija praznih parcela za vlasnike praznog zemljišta.",
    "objection_handling_rule": "Rješavanje prigovora",
    "objection_handling_desc": "Ako se pojave prigovori, zabilježite ih u machine.io. Ako je i dalje „ne”, pitajte: Što bi ovo trebalo imati da biste rekli da? Zabilježite odgovor u machine.io.",
    "data_discipline": "Disciplina podataka",
    "data_discipline_desc": "Svaka interakcija s potencijalnim klijentom mora biti zabilježena i opisana u Supabase / machine.io.",
    "conv_minimum": "Minimum razgovora",
    "conv_minimum_desc": "Ciljajte na barem 1 minutu razgovora uživo po kontaktu — to smanjuje otpor.",
    "operator_support": "Podrška operatera",
    "operator_support_desc": "Koristite Chat za materijale: e-poštu, ugovore, račune, nacrte, taktike, smjernice za izgled, podsjetnike, složenu prodaju velikim klijentima (WHALE), tijekove s više demo prikaza, istraživanje tvrtki i strategije lobiranja.",
    "daily_improvement": "Svakodnevno poboljšanje",
    "daily_improvement_desc": "Učite o proizvodu svaki dan. Kontinuirano ga poboljšavajte.",
    "urgency_framing": "Hitnost i uokvirivanje",
    "urgency_framing_desc": "Svaka interakcija s potencijalnim klijentom je hitna i vođena vrijednošću:",
    "unused_capacity": "Imate neiskorišteni kapacitet.",
    "stop_unauthorized": "Zaustavit ću neovlaštena vozila.",
    "increase_reviews": "Povećat ću broj recenzija, prihod, sigurnost i digitalizaciju.",
    "eliminate_congestion": "Eliminirat ću gužve.",
    "decision_maker_rule": "Pravilo o donositelju odluke",
    "decision_maker_rule_desc": "Nema donositelja odluke = nema zaključenja. Uvijek dođite do donositelja odluke.",

    // Scripts
    "personalized_outreach_framework": "Okvir za personalizirani pristup",
    "outreach_desc": "Mora biti napisano osobno za svakog kupca — radi se o dubini odnosa, a ne o automatizaciji.",
    "outreach_manual_work": "Ručno obavljanje ovog posla za svakog gosta mijenja način na koji razmišljate o prodaji: gradi povjerenje, produbljuje angažman i povećava vjerojatnost uspješnog dogovora.",
    "reference_personalized": "1. Referenca na personaliziranu situaciju (1 rečenica)",
    "acknowledge_context": "Uvažite jedinstveni kontekst ili iskustvo gosta.",
    "present_solution": "2. Predstavite rješenje (1 rečenica)",
    "state_fix": "Samouvjereno iznesite rješenje.",
    "attitude_fix": "Stav: „Ovo je rješenje, a ne prijedlog.”",
    "ask_time_date": "3. Zatražite termin sastanka (1 rečenica)",
    "schedule_follow_up": "Zakažite naknadni poziv ili sastanak kako biste potvrdili rješenje.",
    "attitude_professional": "Stav: profesionalan, samouvjeren, orijentiran na akciju.",
    "follow_up_same_day": "Naknadni kontakt: Uvijek isti dan",
    "send_personalized_note": "Pošaljite personaliziranu rukom pisanu ili AI-potpomognutu PDF bilješku zahvaljujući gostu i predstavljajući sve relevantne informacije s poveznicama.",
    "daily_recap_title": "DNEVNI PREGLED",
    "tasks_summary": "Zadaci: {total} ukupno, {completed} završeno.",
    "no_detailed_records": "Nema detaljnih zapisa za ovaj datum.",
    "from_label_prefix": "Pošiljatelj:",
    "payparq_system": "PayParq sustav",
    "daily_recap_subject": "Dnevni pregled - {date}",
    "map_relevant_lots": "Mapirajte sve relevantne parcele",
    "activate_1_lot_goal": "Aktivirajte 1 parcelu (pokušajte zatvoriti najbolju prvu)",
    "fill_analysis": "Ispunite {type} analizu",
    "hotel": "Hotel",
    "whales_corporation": "Whales korporacija",
    "airport": "Zračna luka",
    "area": "Područje",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('pp_language') as Language;
    if (saved && (saved === 'en' || saved === 'hr')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('pp_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
