var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e3faaf50._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_523a5dec._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17c77370._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a64655ed._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_c7b28d96._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_page_actions_1aa836e2.js")
R.m(50307)
module.exports=R.m(50307).exports
